version: "3.9"
services:
  nginx:
    image: fholzer/nginx-brotli:latest
    container_name: webgl-unity-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/conf:/etc/nginx/conf.d:ro
